### ISSUE TITLE
How do I get list of peers for a given swarm? 

### ISSUE THREAD

**Issue by debunge** [jackpal/Taipei-Torrent#102]
I'm trying to create ui for toy torrent client and so far everything is good, except I cannot locate where peers live.

**Comment by Zilog8** [comment]
The [torrentSession struct has a field "peers", which is type "map[string]*peerState"](https://github.com/jackpal/Taipei-Torrent/blob/master/torrent/torrent.go#L128). This is a map from a string representation of a peer address (e.g. "173.194.123.37:1213") to a [struct that stores the peer's current state](https://github.com/jackpal/Taipei-Torrent/blob/master/torrent/peer.go#L22).

**Comment by debunge** [comment]
Thank you. On a related note, how do I control upload\download limits?

**Comment by Zilog8** [comment]
the upload/download ratio is input as one of the command line arguments. Look for the "seedRatio" flag in main.go.

**Comment by debunge** [comment]
One more question and I will stop bothering you. How do I add torrent from magnet link?

**Comment by Zilog8** [comment]
No bother. From the command-line, just add the magnet link (between quotes) instead of a filepath.
Example: "magnet:?xt=urn:btih:bbb6db69965af769f664b6636e7914f8735141b3"

Here's how it works in a nutshell: Main.go parses the command-line flags, and [passes the leftover arguments to RunTorrents](https://github.com/jackpal/Taipei-Torrent/blob/master/main.go#L164). Then RunTorrents calls a [NewTorrentSession with each argument](https://github.com/jackpal/Taipei-Torrent/blob/master/torrent/torrentLoop.go#L67) string. Finally, [NewTorrentSession](https://github.com/jackpal/Taipei-Torrent/blob/master/torrent/torrent.go#L158) checks the argument string to determine if it's a magnet link or a filepath.

**Comment by debunge** [comment]
Thank you. It is all much clearer now.

**Comment by Zilog8** [comment]
Always glad to help.
