### ISSUE TITLE
A data race reading/writing t.si.HaveTorrent

### ISSUE THREAD

**Issue by jackpal** [jackpal/Taipei-Torrent#69]
A data race reading/writing t.si.HaveTorrent

Noticed while testing the debian magnet link in issue #63

WARNING: DATA RACE
Write by goroutine 10:
  github.com/jackpal/Taipei-Torrent/torrent.(*TorrentSession).load()
      /Users/jackpal/code/gocode/src/github.com/jackpal/Taipei-Torrent/torrent/torrent.go:283 +0x147b
  github.com/jackpal/Taipei-Torrent/torrent.(*TorrentSession).reload()
      /Users/jackpal/code/gocode/src/github.com/jackpal/Taipei-Torrent/torrent/torrent.go:201 +0x356
  github.com/jackpal/Taipei-Torrent/torrent.(*TorrentSession).DoMetadata()
      /Users/jackpal/code/gocode/src/github.com/jackpal/Taipei-Torrent/torrent/torrent.go:1206 +0xe08
  github.com/jackpal/Taipei-Torrent/torrent.(*TorrentSession).DoExtension()
      /Users/jackpal/code/gocode/src/github.com/jackpal/Taipei-Torrent/torrent/torrent.go:1129 +0xa1b
  github.com/jackpal/Taipei-Torrent/torrent.(*TorrentSession).extensionMessage()
      /Users/jackpal/code/gocode/src/github.com/jackpal/Taipei-Torrent/torrent/torrent.go:910 +0xf5
  github.com/jackpal/Taipei-Torrent/torrent.(*TorrentSession).DoMessage()
      /Users/jackpal/code/gocode/src/github.com/jackpal/Taipei-Torrent/torrent/torrent.go:903 +0x138
  github.com/jackpal/Taipei-Torrent/torrent.(*TorrentSession).DoTorrent()
      /Users/jackpal/code/gocode/src/github.com/jackpal/Taipei-Torrent/torrent/torrent.go:602 +0x1f66
  github.com/jackpal/Taipei-Torrent/torrent.func·004()
      /Users/jackpal/code/gocode/src/github.com/jackpal/Taipei-Torrent/torrent/torrentLoop.go:56 +0x3d

Previous read by goroutine 44:
  github.com/jackpal/Taipei-Torrent/torrent.(*TorrentSession).connectToPeer()
      /Users/jackpal/code/gocode/src/github.com/jackpal/Taipei-Torrent/torrent/torrent.go:340 +0x65

Goroutine 10 (running) created at:
  github.com/jackpal/Taipei-Torrent/torrent.RunTorrents()
      /Users/jackpal/code/gocode/src/github.com/jackpal/Taipei-Torrent/torrent/torrentLoop.go:58 +0x69d
  main.main()
      /Users/jackpal/code/gocode/src/github.com/jackpal/Taipei-Torrent/main.go:114 +0x9ca

Goroutine 44 (finished) created at:
  github.com/jackpal/Taipei-Torrent/torrent.(*TorrentSession).DoTorrent()
      /Users/jackpal/code/gocode/src/github.com/jackpal/Taipei-Torrent/torrent/torrent.go:563 +0x1363
  github.com/jackpal/Taipei-Torrent/torrent.func·004()
      /Users/jackpal/code/gocode/src/github.com/jackpal/Taipei-Torrent/torrent/torrentLoop.go:56 +0x3d

**Comment by Zilog8** [comment]
Closing this issue since this race should no longer be possible with commit 0739a68:

The reason for this data race is that in the case of a magnet link torrent, the TorrentSession will start running (and thus connecting peers) before we've had a chance to load the metadata (because we don't have any until peers give it to us). Since peer connections are done in goroutines, TorrentSession.load()'s write t.si.HaveTorrent can race with a TorrentSession.connectToPeer()'s read of t.si.HaveTorrent. Commit 0739a68 removes the read on t.si.HaveTorrent from the peer connection goroutine, since it's actually unnecessary (the check it's doing is already being done before the goroutine is created).
